### ISSUE TITLE
Suggestion: Leverage CSS to hide elements by default

### ISSUE THREAD

**Issue by sean3z** [d1son/SEED#51]
_before_

``` js
$('#divMoreInfoOne').hide();
$("#divMoreInfoTwo").hide();
$("#divMoreInfoThree").hide();
```

_after_

``` css
#divMoreInfoOne, #divMoreInfoTwo, #divMoreInfoThree {
  display: none;
}
```
